= Tips and Tweaking
:toc:

== Tips

* Use `'()` or `[]` instead of `()` in some places to express return
  values, e.g.
+
[source,janet]
----
# => '(:hi 1)
----
or:
+
[source,janet]
----
# => [:hi 1]
----
+
not:
+
[source,janet]
----
# => (:hi 1)
----

* More than one expression + expected value info pair can be placed in
  a comment block.  For example, in the following:
+
[source,janet]
----
(comment

  (+ 1 1)
  # => 2

  (- 1 1)
  # => 0

)
----
+
two tests will be created and executed.

* It's also fine to put other forms in the comment block that don't
  have expected value info appearing after them, all such forms will
  be included in tests.  For example, in the following:
+
[source,janet]
----
(comment

  (def a 1)

  (+ a 1)
  # => 2

)
----
+
`(def a 1)` will be executed during testing.

* However, if a comment block has no tests (i.e. no expected values
  indicated), the forms within the comment block will NOT be executed.
  Thus, for the following:
+
[source,janet]
----
(comment

  (print "hi")

)
----
+
since there are no expected values indicated, `(print "hi")` will
NOT be executed.

== Underlying Details

=== Basics

* The name of the runner script is used to deduce the name of a
  directory containing source files to use for generating tests.  If
  the runner script's name is `examples.janet`, then the corresponding
  directory is `examples` (a direct subdirectory of the project
  directory).

* The directory housing the generated tests is named `.judge_<name>`
  and lives within one's project directory.  `<name>` is determined
  based on the runner script's name as well as where it lives under
  `test`.  This directory and its contents are regenerated each time
  the runner is executed, typically via `jpm test`.

* Test results and output (stdout and stderr) are stored in a
  subdirectory of `.judge_<name>`.  The name of this subdirectory is
  generated each time and it should be very unlikely to lead to
  collisions.

=== Discussion

* The generated directory will contain a copy of the source files from
  which the generated tests are created.  The generated test files are
  modified forms of the original source files and may contain `import`
  forms referring to other source files.  In order for these `import`
  forms to function properly, the original source is copied and thus
  (most ordinary) relative imports should continue to function in the
  context of the generated directory.

* The generated test files use the suffix `.judge`.  This should be
  sufficient to prevent collisions between the names of source files
  (which should have extension `.janet`) and the names of generated
  test files.

* It should be possible to place a runner script within a subdirectory
  of `test`, e.g. a runner script can live in the directory `test/a`.

* It should be possible to use multiple runner scripts, e.g.
  `test/examples.janet` and `test/src.janet`.  Even having both
  `test/a/fun.janet` and `test/b/fun.janet` should work.

* The `<name>` in `.judge_<name>` reflects both the name of the runner
  script as well as the path relative to the `test` directory.

* If the runner script is `test/a/runner.janet`, then the
  corresponding `.judge_<name>` is `.judge_a,example` (note the
  comma).

* If for some reason the path to the runner script has a comma in it,
  it is escaped in the `.judge_<name>` by "doubling".  So if the path
  to the runner script is `test/do,not,use,a,comma,please.janet`, then
  the `.judge_<name>` is `.judge_do,,not,,use,,a,,comma,,please`.

* The use of a single comma in the above manner along with the comma
  doubling / escaping should serve to prevent name collisions.  The
  comma character was chosen based on not having seen it used that
  often in typical source file names.  It is only used by judge-gen
  for the names of directories that will be regenerated and which
  should be safe to delete.

* Co-existence with other testing methods is something the author has
  an interest in.  Please report any encountered issues along these
  lines.
