= Tips and Tweaking
:toc:

== Tips

* Use `'()` or `[]` instead of `()` in some places to express return
  values, e.g.
+
[source,janet]
----
# => '(:hi 1)
----
or:
+
[source,janet]
----
# => [:hi 1]
----
+
not:
+
[source,janet]
----
# => (:hi 1)
----

* More than one expression + expected value info pair can be placed in
  a comment block.  For example, in the following:
+
[source,janet]
----
(comment

  (+ 1 1)
  # => 2

  (- 1 1)
  # => 0

)
----
+
two tests will be created and executed.

* It's also fine to put other forms in the comment block that don't
  have expected value info appearing after them, all such forms will
  be included in tests.  For example, in the following:
+
[source,janet]
----
(comment

  (def a 1)

  (+ a 1)
  # => 2

)
----
+
`(def a 1)` will be executed during testing.

* However, if a comment block has no tests (i.e. no expected values
  indicated), the forms within the comment block will NOT be executed.
  Thus, for the following:
+
[source,janet]
----
(comment

  (print "hi")

)
----
+
since there are no expected values indicated, `(print "hi")` will
NOT be executed.

== Tweaking

=== Fine Tuning Configuration

* By default, the directory housing the tests is named `.judge`
  and lives within one's project directory.  If that name is a problem
  (e.g. your project is already using it or wants to use it), there is
  a way to select a different name.

* By default, the generated test files all start with the prefix
  `judge-`.  A file that starts with that prefix is treated as a test
  file.  The prefix may be configured to be something else though, so
  if any of your source files uses that prefix, please choose a prefix
  that is not used by any of your source files.

These things can be configured by editing the runner file
appropriately.

=== Using judge-gen With Other Testing Methods

Co-existence with other testing methods is something the author has an
interest in.  Please report any encountered issues along these lines.
