= Tips and Tweaking
:toc:

== Tips

* Use `'()` or `[]` instead of `()` in some places to express return
  values, e.g.
+
[source,janet]
----
# => '(:hi 1)
----
or:
+
[source,janet]
----
# => [:hi 1]
----
+
not:
+
[source,janet]
----
# => (:hi 1)
----

* More than one expression + expected value info pair can be placed in
  a comment block.  For example, in the following:
+
[source,janet]
----
(comment

  (+ 1 1)
  # => 2

  (- 1 1)
  # => 0

)
----
+
two tests will be created and executed.

* It's also fine to put other forms in the comment block that don't
  have expected value info appearing after them, all such forms will
  be included in tests.  For example, in the following:
+
[source,janet]
----
(comment

  (def a 1)

  (+ a 1)
  # => 2

)
----
+
`(def a 1)` will be executed during testing.

* However, if a comment block has no tests (i.e. no expected values
  indicated), the forms within the comment block will NOT be executed.
  Thus, for the following:
+
[source,janet]
----
(comment

  (print "hi")

)
----
+
since there are no expected values indicated, `(print "hi")` will
NOT be executed.

== Tweaking

=== Fine Tuning Configuration

Although currently there is no configuration file apart from the
runner script itself, effort has been put into not having to edit the
runner script and still be able to perform some configuration.  Please
try the route of changing the name and/or location of the runner
script to see if that works for you.  The following provides some
related details.

* By default, the runner script's name (without the file extension) is
  used to identify the direct subdirectory of the project directory
  that the files used to generate tests live in.  In the Setup
  instructions in the README, the name `examples` corresponds to this.
  So if the runner script's name is `examples.janet`, then the project
  directory should have a direct subdirectory named `examples`.  When
  `jpm test` is invokved, the content of the `examples` directory is
  used to generate test files in another directory (typically named
  `.judge_<name>`, see following point for details) and the generated
  tests are subsequently executed.

* By default, the directory housing the generated tests is named
  `.judge_<name>` and lives within one's project directory.  `<name>`
  is determined based on the runner script's name as well as where it
  lives under `test`.  This directory and its contents are regenerated
  each time the runner is executed.  (There is a way to select a
  different `<name>`, but if that is done by editing the runner script
  and if you happen to want to use multiple runner scripts, it is up
  to you to ensure collisions of names as well as files and
  directories do not occur.)

* By default, the generated test files all start with the prefix
  `judge-`.  A file that starts with that prefix is treated as a test
  file.  The prefix may be configured to be something else though, so
  if any of your source files uses that prefix, please choose a prefix
  that is not used by any of your source files.

These things can be configured by editing the runner file
appropriately.

=== Using judge-gen With Other Testing Methods

Co-existence with other testing methods is something the author has an
interest in.  Please report any encountered issues along these lines.
